version: '3'
services:
  app:
    build: .
    container_name: lib_rest_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    env_file:
      - ./app/.env
      
  postgresdb:
    image: postgres:latest
    container_name: lib_postgresdb
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:


    